### ISSUE TITLE
 Server Error (500)  in Windows 10 installation

### ISSUE THREAD

**Issue by carlosuema** [cyllab/CalcUS#7]
In terminal one get this message:

calcus-master-postgres-1     | 2022-03-29 15:43:25.079 UTC [44] ERROR:  relation "frontend_example" does not exist at character 97
calcus-master-postgres-1     | 2022-03-29 15:43:25.079 UTC [44] STATEMENT:  SELECT "frontend_example"."id", "frontend_example"."title", "frontend_example"."page_path" FROM "frontend_example" LIMIT 21
calcus-master-web-1          | 2022-03-29 10:43:25,052 [ERROR]  log: Internal Server Error: /learn/
calcus-master-web-1          | Traceback (most recent call last):
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
calcus-master-web-1          |     return self.cursor.execute(sql, params)
calcus-master-web-1          | psycopg2.errors.UndefinedTable: relation "frontend_example" does not exist
calcus-master-web-1          | LINE 1: ...ple"."title", "frontend_example"."page_path" FROM "frontend_...
calcus-master-web-1          |                                                              ^
calcus-master-web-1          |
calcus-master-web-1          |
calcus-master-web-1          | The above exception was the direct cause of the following exception:
calcus-master-web-1          |
calcus-master-web-1          | Traceback (most recent call last):
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
calcus-master-web-1          |     response = get_response(request)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
calcus-master-web-1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
calcus-master-web-1          |   File "/calcus/frontend/views.py", line 916, in learn
calcus-master-web-1          |     return render(
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
calcus-master-web-1          |     content = loader.render_to_string(template_name, context, request, using=using)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
calcus-master-web-1          |     return template.render(context, request)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
calcus-master-web-1          |     return self.template.render(context)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 170, in render
calcus-master-web-1          |     return self._render(context)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
calcus-master-web-1          |     return self.nodelist.render(context)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
calcus-master-web-1          |     bit = node.render_annotated(context)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
calcus-master-web-1          |     return self.render(context)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
calcus-master-web-1          |     return compiled_parent._render(context)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
calcus-master-web-1          |     return self.nodelist.render(context)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
calcus-master-web-1          |     bit = node.render_annotated(context)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
calcus-master-web-1          |     return self.render(context)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
calcus-master-web-1          |     result = block.nodelist.render(context)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
calcus-master-web-1          |     bit = node.render_annotated(context)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
calcus-master-web-1          |     return self.render(context)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 171, in render
calcus-master-web-1          |     len_values = len(values)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 262, in __len__
calcus-master-web-1          |     self._fetch_all()
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
calcus-master-web-1          |     self._result_cache = list(self._iterable_class(self))
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
calcus-master-web-1          |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
calcus-master-web-1          |     cursor.execute(sql, params)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
calcus-master-web-1          |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
calcus-master-web-1          |     return executor(sql, params, many, context)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
calcus-master-web-1          |     return self.cursor.execute(sql, params)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
calcus-master-web-1          |     raise dj_exc_value.with_traceback(traceback) from exc_value
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
calcus-master-web-1          |     return self.cursor.execute(sql, params)
calcus-master-web-1          | django.db.utils.ProgrammingError: relation "frontend_example" does not exist
calcus-master-web-1          | LINE 1: ...ple"."title", "frontend_example"."page_path" FROM "frontend_...
calcus-master-web-1          |                                                              ^
calcus-master-web-1          |
calcus-master-web-1          | 172.22.0.8 - - [29/Mar/2022:10:43:25 -0500] "GET /learn/ HTTP/1.0" 500 145 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36"

 

In browser one get this:

![image](https://user-images.githubusercontent.com/1608241/160652075-da718453-7ae0-48ef-b345-d3be7ec9a7ae.png)

**Configuration**
- Using prebuild Docker container (default).
- Host operating system (Windows 10)

**Comment by RaphaelRobidas** [comment]
Thanks for reporting this issue. I did not get the same error on Windows, but I encountered a permission error which could be the source of the problem. Try replacing `docker-compose.yml` by this file: [docker-compose.txt](https://github.com/cyllab/CalcUS/files/8373352/docker-compose.txt) (I had to change the extension so Github would accept it, but it needs to be a .yml file to work). If you have used `generate_env.bat` before last sunday, you may need to change `version: "3"` into `version: "3.4"` in `docker-compose.override.yml`. If you downloaded the code a while ago, you could need to update it by downloading the latest release (you can migrate `data`, `.env` and `docker-compose.override.yml` to the new directory).

Let me know if it solves your issue.

**Comment by carlosuema** [comment]
Thanks for the answer!

This issue still persits. However, only when I have to login and it trow a new error message:

calcus-master-web-1          | Superuser account found, creation aborted
calcus-master-web-1          | [2022-03-29 17:05:33 +0000] [48] [INFO] Starting gunicorn 20.1.0
calcus-master-web-1          | [2022-03-29 17:05:33 +0000] [48] [INFO] Listening at: http://0.0.0.0:8000 (48)
calcus-master-web-1          | [2022-03-29 17:05:33 +0000] [48] [INFO] Using worker: sync
calcus-master-web-1          | [2022-03-29 17:05:33 +0000] [49] [INFO] Booting worker with pid: 49
calcus-master-web-1          | 172.18.0.8 - - [29/Mar/2022:12:25:11 -0500] "GET /home/ HTTP/1.0" 200 4779 "http://localhost:8080/accounts/login/?next=/projects/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
calcus-master-web-1          | 172.18.0.8 - - [29/Mar/2022:12:25:15 -0500] "GET /learn/ HTTP/1.0" 200 5749 "http://localhost:8080/home/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
calcus-master-web-1          | 172.18.0.8 - - [29/Mar/2022:12:25:17 -0500] "GET /projects/ HTTP/1.0" 302 0 "http://localhost:8080/learn/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
calcus-master-web-1          | 172.18.0.8 - - [29/Mar/2022:12:25:17 -0500] "GET /accounts/login/?next=/projects/ HTTP/1.0" 200 5706 "http://localhost:8080/learn/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
calcus-master-web-1          | 2022-03-29 12:25:20,446 [ERROR]  log: Internal Server Error: /accounts/login/
calcus-master-web-1          | Traceback (most recent call last):
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
calcus-master-web-1          |     response = get_response(request)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
calcus-master-web-1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
calcus-master-web-1          |     return self.dispatch(request, *args, **kwargs)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
calcus-master-web-1          |     return bound_method(*args, **kwargs)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
calcus-master-web-1          |     return view(request, *args, **kwargs)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
calcus-master-web-1          |     return bound_method(*args, **kwargs)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
calcus-master-web-1          |     response = view_func(request, *args, **kwargs)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
calcus-master-web-1          |     return bound_method(*args, **kwargs)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
calcus-master-web-1          |     response = view_func(request, *args, **kwargs)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/views.py", line 63, in dispatch
calcus-master-web-1          |     return super().dispatch(request, *args, **kwargs)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
calcus-master-web-1          |     return handler(request, *args, **kwargs)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/edit.py", line 142, in post
calcus-master-web-1          |     return self.form_valid(form)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/views.py", line 92, in form_valid
calcus-master-web-1          |     auth_login(self.request, form.get_user())
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 135, in login
calcus-master-web-1          |     user_logged_in.send(sender=user.__class__, request=request, user=user)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 180, in send
calcus-master-web-1          |     return [
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
calcus-master-web-1          |     (receiver, receiver(signal=self, sender=sender, **named))
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/models.py", line 22, in update_last_login
calcus-master-web-1          |     user.save(update_fields=['last_login'])
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 67, in save
calcus-master-web-1          |     super().save(*args, **kwargs)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 739, in save
calcus-master-web-1          |     self.save_base(using=using, force_insert=force_insert,
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 787, in save_base
calcus-master-web-1          |     post_save.send(
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 180, in send
calcus-master-web-1          |     return [
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
calcus-master-web-1          |     (receiver, receiver(signal=self, sender=sender, **named))
calcus-master-web-1          |   File "/calcus/frontend/models.py", line 1010, in save_user_profile
calcus-master-web-1          |     instance.profile.save()
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 421, in __get__
calcus-master-web-1          |     raise self.RelatedObjectDoesNotExist(
calcus-master-web-1          | django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
calcus-master-web-1          | 172.18.0.8 - - [29/Mar/2022:12:25:20 -0500] "POST /accounts/login/ HTTP/1.0" 500 145 "http://localhost:8080/accounts/login/?next=/projects/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
calcus-master-web-1          | 172.18.0.8 - - [29/Mar/2022:12:25:22 -0500] "GET /accounts/login/?next=/projects/ HTTP/1.0" 200 5706 "http://localhost:8080/learn/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
calcus-master-web-1          | 2022-03-29 12:25:29,801 [ERROR]  log: Internal Server Error: /accounts/login/
calcus-master-web-1          | Traceback (most recent call last):
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
calcus-master-web-1          |     response = get_response(request)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
calcus-master-web-1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
calcus-master-web-1          |     return self.dispatch(request, *args, **kwargs)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
calcus-master-web-1          |     return bound_method(*args, **kwargs)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
calcus-master-web-1          |     return view(request, *args, **kwargs)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
calcus-master-web-1          |     return bound_method(*args, **kwargs)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
calcus-master-web-1          |     response = view_func(request, *args, **kwargs)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
calcus-master-web-1          |     return bound_method(*args, **kwargs)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
calcus-master-web-1          |     response = view_func(request, *args, **kwargs)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/views.py", line 63, in dispatch
calcus-master-web-1          |     return super().dispatch(request, *args, **kwargs)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
calcus-master-web-1          |     return handler(request, *args, **kwargs)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/edit.py", line 142, in post
calcus-master-web-1          |     return self.form_valid(form)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/views.py", line 92, in form_valid
calcus-master-web-1          |     auth_login(self.request, form.get_user())
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 135, in login
calcus-master-web-1          |     user_logged_in.send(sender=user.__class__, request=request, user=user)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 180, in send
calcus-master-web-1          |     return [
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
calcus-master-web-1          |     (receiver, receiver(signal=self, sender=sender, **named))
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/models.py", line 22, in update_last_login
calcus-master-web-1          |     user.save(update_fields=['last_login'])
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 67, in save
calcus-master-web-1          |     super().save(*args, **kwargs)
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 739, in save
calcus-master-web-1          |     self.save_base(using=using, force_insert=force_insert,
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 787, in save_base
calcus-master-web-1          |     post_save.send(
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 180, in send
calcus-master-web-1          |     return [
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
calcus-master-web-1          |     (receiver, receiver(signal=self, sender=sender, **named))
calcus-master-web-1          |   File "/calcus/frontend/models.py", line 1010, in save_user_profile
calcus-master-web-1          |     instance.profile.save()
calcus-master-web-1          |   File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 421, in __get__
calcus-master-web-1          |     raise self.RelatedObjectDoesNotExist(
calcus-master-web-1          | django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
calcus-master-web-1          | 172.18.0.8 - - [29/Mar/2022:12:25:29 -0500] "POST /accounts/login/ HTTP/1.0" 500 145 "http://localhost:8080/accounts/login/?next=/projects/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"

**Comment by RaphaelRobidas** [comment]
Hello,

Did it work before or are you running CalcUS for the first time? It looks as though the database has not been created correctly, which might be because of the previous permission error. If this is the case, you can delete the `data` subdirectory and start CalcUS again. The database will be recreated (hopefully) correctly.

**Comment by RaphaelRobidas** [comment]
@carlosuema Did you manage to solve the problem? If so, you can close this issue.

**Comment by RaphaelRobidas** [comment]
Closing due to inactivity
